### PR TITLE
Solve breaking changes after update to ESLint 2.0.0

### PR DESCRIPTION
**Pull request by lkrnac**
This pull request replaces this one: https://github.com/walmartlabs/eslint-config-defaults/pull/68
It doesn't contain major version bump.

### CODE REVIEW

**Comment by tgandrews** [comment]
This looks good.

**Comment by divmain** [comment]
@lkrnac since this resolves some issues for me, I've published your PR as `@divmain/eslint-config-defaults`.  Looks like there are some other requirements that @baer has in mind for full ESLint v2 compatibility, so I'll unpublish as soon as #69 is closed.

**Comment by baer** [comment]
I'm going to merge this, remove the package.json bump to 2.x and publish as a patch. This should unbreak those early adopters that just cannot wait to use eslint 2 before I can finish the work to fully convert this lib.

Hope this helps @divmain @tgandrews @lkrnac. Thanks for the contribution!.

**Comment by baer** [comment]
Okay, I merged this to master but I can't publish without doing a major rev since this replaces rules from 1.x with rules added in 2.x. For this reason I have to hold off on releasing until 2.x work is further along. You can depend on master in your project if you'd like though...

Sorry :(

**Comment by divmain** [comment]
@baer, could you do a pre-major release?  That would allow folks to explicitly use these changes, it wouldn't effect current ESLint 1.x users, and it would indicate that this is an iteration in the direction of a break-change-release.

**Comment by divmain** [comment]
Also, thanks :)

**Comment by baer** [comment]
:weary: Damn you npm

```
npm ERR! Tag name must not be a valid SemVer range: 10.0.0-alpha1
npm ERR! Tag name must not be a valid SemVer range: 10.0.0-alpha.1
npm ERR! Tag name must not be a valid SemVer range: 10.0.0-1
```

**Comment by baer** [comment]
screen shot 2016-03-09 at 3 16 16 pm


Published @alpha. Sorry for the delay.

**Pull request merged**
